# Generated by Django 2.2.2 on 2019-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190615_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='encrypted_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
