# Generated by Django 2.2.2 on 2019-06-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190615_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='encrypted_id',
            field=models.CharField(max_length=100),
        ),
    ]
