# Generated by Django 2.2.2 on 2019-06-19 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20190619_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SirGay', max_length=100)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('encrypted_id', models.CharField(blank=True, max_length=100)),
                ('level', models.PositiveIntegerField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retards', to='accounts.Profile')),
            ],
        ),
    ]
